const Popup = (project) => {
  const backdrop = document.createElement('div');
  backdrop.className = 'backdrop';
  document.body.appendChild(backdrop);
  const popup = document.createElement('div');
  popup.className = 'popup';
  backdrop.appendChild(popup);
  const popupHeader = document.createElement('div');
  popupHeader.className = 'popup-header';
  popup.appendChild(popupHeader);
  const h1 = document.createElement('h1');
  h1.innerText = project.name;
  h1.classList = 'project-name';
  popupHeader.appendChild(h1);
  const exit = document.createElement('a');
  exit.addEventListener('click', () => {
    backdrop.remove();
  });
  exit.innerHTML = '<img src="./images/cancel.png">';
  exit.classList = 'exit';
  popupHeader.appendChild(exit);
  const div = document.createElement('div');
  div.classList = 'popup-data';
  popup.appendChild(div);
  const h4 = document.createElement('h4');
  h4.innerText = project.client;
  h4.className = 'project-client';
  div.appendChild(h4);
  const img2 = document.createElement('img');
  img2.setAttribute('src', './images/Counter.png');
  img2.className = 'counter';
  div.appendChild(img2);
  const span = document.createElement('span');
  span.className = 'programming-language';
  span.innerText = 'Back End Dev';
  div.appendChild(span);
  const img3 = document.createElement('img');
  img3.setAttribute('src', './images/Counter.png');
  img3.className = 'counter';
  div.appendChild(img3);
  const span2 = document.createElement('span');
  span2.className = 'year';
  span2.innerText = project.year;
  div.appendChild(span2);
  const div2 = document.createElement('div');
  div2.className = 'popup-image';
  popup.appendChild(div2);
  const img = document.createElement('img');
  img.className = 'project-image';
  img.setAttribute('src', project.img);
  div2.appendChild(img);
  const cardBody = document.createElement('div');
  cardBody.className = 'popup-flex';
  popup.appendChild(cardBody);
  const p = document.createElement('p');
  p.className = 'popup-paragraph';
  p.innerText = project.description;
  cardBody.appendChild(p);
  const buttonContainer = document.createElement('div');
  buttonContainer.className = 'button-container';
  cardBody.appendChild(buttonContainer);
  const ul = document.createElement('ul');
  ul.className = 'languages';
  buttonContainer.appendChild(ul);
  project.technologies.forEach((technology) => {
    const li = document.createElement('li');
    li.className = 'dev-tool';
    li.innerText = technology;
    ul.appendChild(li);
  });
  const btnDiv = document.createElement('div');
  btnDiv.className = 'btn-div';
  buttonContainer.appendChild(btnDiv);
  const button = document.createElement('button');
  button.className = 'btn';
  button.innerText = 'See Live';
  button.addEventListener('click', () => {
    window.location = project.liveVersion;
  });
  const icon = document.createElement('img');
  icon.setAttribute('src', './images/Brokenlink.png');
  button.append(icon);
  btnDiv.appendChild(button);
  const button2 = document.createElement('button');
  button2.className = 'btn';
  button2.innerText = 'See Source';
  button2.addEventListener('click', () => {
    window.location = project.source;
  });
  const icon2 = document.createElement('img');
  icon2.setAttribute('src', './images/github.png');
  button2.append(icon2);
  btnDiv.appendChild(button2);
};

export default Popup;
